name: Node.js CI
env:
  env: ${{ secrets.ENV }}
  serviceAccountKey: ${{ secrets.SERVICE_ACCOUNT_KEY }}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - env:
         JWT_SECRET: ${{ secrets.MY_CLIENT_ID }}
         FIREBASE_BUCKET_LOCATION: ${{ secrets.FIREBASE_BUCKET_LOCATION }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test 
