name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DOT_ENV: ${{ secrets.ENV }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo  $DOT_ENV | base64 --decode > .env
      - run: echo  $SERVICE_ACCOUNT_KEY | base64 --decode > services/firebase/serviceAccountKey.json
      - run: echo  $DOT_ENV
      - run: echo 'bGludXhoaW50LmNvbQo=' | base64 --decode
      - run: cat -n .env
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test 
