name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  env: ${{ secrets.ENV }}
  serviceAccountKey: ${{ secrets.SERVICE_ACCOUNT_KEY }}
jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo  $env | base64 --decode > .env
      - run: echo  $serviceAccountKey | base64 --decode > services/firebase/serviceAccountKey.json
      - run: echo  $env
      - run: echo 'bGludXhoaW50LmNvbQo=' | base64 --decode
      - run: cat -n .env
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test 
