name: Node.js CI
env:
  env: ${{ secrets.ENV }}
  serviceAccountKey: ${{ secrets.SERVICE_ACCOUNT_KEY }}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
         ENV: ${{ secrets.ENV }}
         SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
         run: |
           echo  $ENV | base64 --decode > .env
           echo  $SERVICE_ACCOUNT_KEY | base64 --decode > services/firebase/serviceAccountKey.json
           echo  $ENV
           echo 'bGludXhoaW50LmNvbQo=' | base64 --decode
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test 
